### ISSUE TITLE
Do not upload codes if the contest is still live.

### ISSUE THREAD

**Issue by sibasish14** [rajprakash00/BYTE-TO-BIT_CODECHEF#1]
@rajprakash00 I see that you have uploaded your code for `BITOBYT`. What if I just copy your code, change variable names and submit it. I'll be getting full points and reduce your chance of winning any prize money. **Worst case**- someone simply does a copy&paste work. This will result in that guy's account, as well as yours to be suspended. You don't want that right? 

Look at my repository, I always upload codes after the contest. Hence I suggest you to delete this repository for now. Later on, when the contest is over, create a new one.

^^ The same goes for your other repos.

Happy Coding :)

**Comment by rajprakash00** [comment]
oh!! thanks @sibasish14  bhaiya for your valuable suggestion.Actually i didn't upload it intentionally but still i will think about this suggestion before uploading any code.
THANKS!!AGAIN.

**Comment by ashish493** [comment]
Well @rajprakash00  as the contest is over,
You can upload your code...
